# Generated by Django 4.2.6 on 2023-10-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=225)),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_title", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("fax", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("title_of_courtesy", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("hire_date", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("home_phone", models.CharField(max_length=100)),
                ("extension", models.CharField(max_length=100)),
                (
                    "reports_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="northwind.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("required_date", models.DateField()),
                ("shipped_date", models.DateField()),
                ("freight", models.DecimalField(decimal_places=3, max_digits=3)),
                ("ship_name", models.CharField(max_length=100)),
                ("ship_address", models.CharField(max_length=100)),
                ("ship_city", models.CharField(max_length=100)),
                ("ship_region", models.CharField(max_length=100)),
                ("ship_postal_code", models.CharField(max_length=100)),
                ("ship_country", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_order",
                        to="northwind.customer",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_order",
                        to="northwind.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shipper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=225)),
                ("contact_name", models.CharField(max_length=225)),
                ("contact_title", models.CharField(max_length=225)),
                ("address", models.CharField(max_length=225)),
                ("city", models.CharField(max_length=225)),
                ("region", models.CharField(max_length=225)),
                ("postal_code", models.CharField(max_length=225)),
                ("country", models.CharField(max_length=225)),
                ("phone", models.CharField(max_length=225)),
                ("fax", models.CharField(max_length=225)),
                ("home_page", models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="northwind.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("quantity_per_unit", models.CharField(max_length=50)),
                ("unit_price", models.DecimalField(decimal_places=3, max_digits=3)),
                ("units_in_stock", models.IntegerField()),
                ("units_on_order", models.IntegerField()),
                ("reorder_level", models.IntegerField()),
                ("discontinued", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_category",
                        to="northwind.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_supplier",
                        to="northwind.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("discount", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="northwind.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="northwind.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="ship_via",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="northwind.shipper",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="northwind.employee",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="northwind.territory",
                    ),
                ),
            ],
        ),
    ]
