# Generated by Django 4.2.6 on 2023-10-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("northwind", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="freight",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="discount",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
