# Generated by Django 4.2.6 on 2023-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("northwind", "0002_alter_order_freight_alter_orderdetail_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
