# Generated by Django 4.2.6 on 2023-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("northwind", "0003_alter_employee_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="required_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
