medical_specializations = [
    "Cardiologist",
    "Dermatologist",
    "Pediatrician",
    "Oncologist",
    "Neurologist",
    "Gastroenterologist",
    "Orthopedic Surgeon",
    "Ophthalmologist",
    "Otolaryngologist (ENT)",
    "Obstetrician-Gynecologist (OB/GYN)",
    "Urologist",
    "Rheumatologist",
    "Psychiatrist",
    "Pulmonologist",
    "Endocrinologist",
    "Allergist/Immunologist",
    "Nephrologist",
    "Infectious Disease Specialist",
    "Gynecologic Oncologist",
    "Hematologist",
    "Geriatrician",
    "Intensivist",
    "Neonatologist",
    "Pain Management Specialist",
    "Plastic Surgeon",
    "Sports Medicine Physician",
    "Forensic Pathologist",
    "Radiologist",
    "Pathologist",
    "Emergency Medicine Physician",
]

allergies = [
    "Pollen Allergy",
    "Dust Mite Allergy",
    "Pet Allergy (Animal Dander)",
    "Food Allergies",
    "Insect Sting Allergy",
    "Drug Allergies",
    "Latex Allergy",
    "Mold Allergy",
    "Hay Fever (Allergic Rhinitis)",
    "Asthma",
    "Eczema (Atopic Dermatitis)",
    "Contact Dermatitis",
    "Peanut Allergy",
    "Tree Nut Allergy",
    "Milk Allergy",
    "Egg Allergy",
    "Shellfish Allergy",
    "Soy Allergy",
    "Wheat Allergy",
    "Sesame Allergy",
    "Sun Allergy (Photosensitivity)",
    "Cold Urticaria (Cold Allergy)",
    "Chronic Urticaria (Hives)",
]


diagnoses = [
    "Hypertension (High Blood Pressure)",
    "Diabetes",
    "Coronary Artery Disease",
    "Asthma",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Osteoarthritis",
    "Rheumatoid Arthritis",
    "Hyperlipidemia (High Cholesterol)",
    "Gastroesophageal Reflux Disease (GERD)",
    "Anxiety Disorders",
    "Depression",
    "Migraine",
    "Atrial Fibrillation",
    "Chronic Kidney Disease",
    "Cancer",
    "Stroke",
    "Obesity",
    "Alzheimer's Disease",
    "Celiac Disease",
    "Irritable Bowel Syndrome (IBS)",
    "Parkinson's Disease",
    "Multiple Sclerosis",
    "Hypothyroidism",
    "Hyperthyroidism",
    "Lupus (Systemic Lupus Erythematosus)",
    "Epilepsy",
    "Bipolar Disorder",
    "Schizophrenia",
    "HIV/AIDS",
    "Influenza (Flu)",
    "COVID-19 (Coronavirus Disease 2019)",
    "Tuberculosis (TB)",
    "Hepatitis",
    "Pneumonia",
    "Osteoporosis",
    "Autism Spectrum Disorder",
]
