# Generated by Django 4.2.6 on 2023-10-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, default="Python.png", null=True, upload_to="category_images"
            ),
        ),
    ]
