# Generated by Django 4.2.6 on 2023-10-07 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
