# Generated by Django 4.2.6 on 2023-10-07 13:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
